name: linux_ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # get latest code and submodules
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      # install the latest cmake and ninja
      - uses: lukka/get-cmake@latest
      # Setup vcpkg
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          setupOnly: true 
      - name: 'Update apt' 
        shell: 'bash'
        run: 'sudo apt-get update'
      - name: 'Apt dependencies'
        shell: 'bash'
        run: 'sudo apt install g++-11 libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev'
      - name: 'Configure and build'
        run: |
          cmake --preset linux-release
          cmake --build --preset linux-release-rebuild
